def c1 = g.addV(label, 'customer', 'name', cName1, 'age', age1).next()
def c2 = g.addV(label, 'customer', 'name', cName2, 'age', age2).next()
def v1 = g.V(c1.id()).next()
def v2 = g.V(c2.id()).next()
v1.addEdge('related', v2)